name: Semver Bump
description: "Bump Semantic Version"
author: "Oleg Sucharevich"
branding:
  icon: git-merge
  color: green
inputs:
  version:
    description: "A valid semantic version"
    required: false
    default: ""
  version_file:
    description: "Load version from file (it should the only line in the file)"
    required: false
    default: ""
  bump: 
    description: "Type of the bump"
    default: "patch"
    required: false
  bump_file: 
    description: "Load bump from file (it should the only line in the file)"
    default: ""
    required: false
outputs:
  version:
    description: "The bumped version"
runs:
  using: "docker"
  image: "docker://olsynt/semver:1.0.0"
  args:
    - semver
    - --version
    - ${{ inputs.version }}
    - --version-file
    - ${{ inputs.version_file }}
    - --bump
    - ${{ inputs.bump }}
    - --bump-file
    - ${{ inputs.bump_file }}